# Generated by Django 5.2.5 on 2025-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrowing_terms',
            field=models.CharField(help_text='e.g., Free for 1 week, Rs.500.00 deposit required', max_length=255),
        ),
    ]
