# Generated by Django 5.2.5 on 2025-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_item_borrowing_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount (e.g., 500.00)', max_digits=10, null=True),
        ),
    ]
