# Generated by Django 5.2.5 on 2025-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_item_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ON_LOAN', 'On Loan'), ('AWAITING_DEPOSIT', 'Awaiting Deposit'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
