# Generated by Django 5.2.5 on 2025-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_borrowrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rental_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rental fee for the item (e.g., 50.00)', max_digits=10, null=True),
        ),
    ]
