# Generated by Django 5.2.5 on 2025-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_item_rental_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='borrowing_period',
            field=models.PositiveIntegerField(default=7, help_text='Maximum borrowing period in days (e.g., 7)'),
        ),
    ]
